name: Busted

on: [push, pull_request]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v2

            - name: get lua
              uses: leafo/gh-actions-lua@v10
              with:
                luaVersion: "5.1"

            - name: get luarocks
              uses: leafo/gh-actions-luarocks@v4
              with:
                luaVersion: "5.1"

            - name: get busted and luasocket
              run: |
                luarocks install busted
                luarocks install luasocket
            
            - name: debug
              run: |
                ls -l /home/runner/work/script-manager/script-manager/.luarocks
                ls -l /home/runner/work/script-manager/script-manager/.luarocks/share
                ls -l /home/runner/work/script-manager/script-manager/.luarocks/lib
                ls -l /home/runner/work/script-manager/script-manager/.luarocks/etc
                ls -l /home/runner/work/script-manager/script-manager/.luarocks/bin
                ls -l /home/runner/work/script-manager/script-manager/.luarocks/share/lua/5.1/
                ls -l /home/runner/work/script-manager/script-manager/.luarocks/share/lua/5.1/socket

                

            - name: run tests
              run: |
                busted .
