name: Busted

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - uses: leafo/gh-actions-lua@v10
      with:
        luaVersion: "5.1.5"

    - uses: leafo/gh-actions-luarocks@v4
      with:
        luaVersion: "5.1.5"

    - name: build
      run: |
        luarocks install busted
        luarocks make

    - name: test
      run: |
        busted .
