name: test

on: [push, pull_request]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v2

            - name: get lua
              uses: leafo/gh-actions-lua@v10
              with:
                luaVersion: "5.1"

            - name: get luarocks
              uses: leafo/gh-actions-luarocks@v4

            - name: get busted and luasocket
              run: |
                luarocks install busted
                luarocks install luasocket

            - name: echo stuff
              run:
                echo ls -l /usr
                echo ls -l /usr/share
                echo ls -l /usr/share/lua
                echo ls -l /usr/share/lua/5.1

            - name: fix https
              run: |
                mkdir -p /usr/share/lua/5.1/ssl/
                ln -s /usr/share/lua/5.1/https.lua /usr/share/lua/5.1/ssl/https.lua

            - name: run tests
              run: |
                busted .
