name: Busted

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: get lua
      uses: leafo/gh-actions-lua@v10
      with: 
        luaVersion: "5.1"

    - name: get luarocks
      uses: leafo/gh-actions-luarocks@v4
      with: 
        luaVersion: "5.1"

    - name: get busted and luasocket
      run: |
        luarocks install busted
        luarocks install luasocket
        luarocks install luasec

    - name: test
      run: |
        busted .
