name: Busted
on: [push, pull_request]
jobs:
  sile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        run: |
            docker pull ghcr.io/lunarmodules/busted:latest
            docker run -v "$(pwd):/data" ghcr.io/lunarmodules/busted:latest specs